### PR TITLE
Possibility to define requirements for redirects

### PR DESCRIPTION
**Pull request by leonverschuren**
Added the possibility to add Symfony route requirements to a redirect.

### CODE REVIEW

**Comment by rvanlaarhoven** [comment]
I think creating a complete new model only for the redirect requirements is too much overhead. I suggest storing the requirements as a simple serialized array (e.g. Doctrine `json_array`).

Also, I'm not sure since what Symfony version the controller type-hinting got supported natively?

**Comment by leonverschuren** [comment]
Type-hinting is a feature of the SensioFrameworkExtraBundle supported since 2.0 (3.0 is the current version). Since it's not a native Symfony function, perhaps I should revert these changes?

**Comment by rvanlaarhoven** [comment]
Yeah I think that would be better

**Comment by rvanlaarhoven** [comment]
Hi @leonverschuren , I completely forgot about this PR. Could you fix the merge conflicts?

Also, is there a reason why you added `braincrafted/bootstrap-bundle` to the Composer require section?

**Comment by leonverschuren** [comment]
I added the `braincrafted/bootstrap-bundle` reference because the FormType uses the `bootstrap_collection` to dynamically add and remove requirements. Do you have an idea to remove the requirement?

Should I fix the Forms for Symfony 3?

**Comment by rvanlaarhoven** [comment]
Hmm, not sure. Don't want to require a complete bundle for one form field, but also want to give the possibility to easily add requirements.

Maybe use the original `collection` type with the basic javascript as shown on this page; http://symfony.com/doc/current/reference/forms/types/collection.html.

**Pull request merged**
